import Foundation

/// Everything the agent can be asked to do, by name.
///
/// A superset of V1's tools: the ten native ones are wrapped unchanged, and V2 adds the ones a
/// job needs — reading the user's own documents and world, writing an artifact, asking a question.
/// Anything outside this list cannot be generated by the planner, cannot pass validation, and
/// cannot be executed.
public struct CapabilityID: RawRepresentable, Hashable, Sendable, Codable, CustomStringConvertible {
    public let rawValue: String
    public init(rawValue: String) { self.rawValue = rawValue }
    public init(_ rawValue: String) { self.rawValue = rawValue }
    public init(_ tool: ToolID) { rawValue = tool.rawValue }
    public var description: String { rawValue }

    /// The V1 tool this capability is, when it is one.
    public var tool: ToolID? { ToolID(rawValue: rawValue) }

    // Reading the user's own world and documents (local, no permission, no risk).
    public static let searchKnowledge = CapabilityID("search_knowledge")
    public static let readDocument = CapabilityID("read_document")
    public static let searchIntelligence = CapabilityID("search_intelligence")
    /// Writing something down for the user, as an artifact they can read and keep.
    public static let writeArtifact = CapabilityID("write_artifact")
    /// Recording something learned in the course of a job, through the memory pipeline.
    public static let remember = CapabilityID("remember")
    /// Stopping to ask the user a question the job cannot answer for itself.
    public static let askUser = CapabilityID("ask_user")
    /// Looking something up in the world. Leaves the device, so it is gated, logged and refusable.
    public static let searchWeb = CapabilityID("search_web")
    public static let readWebPage = CapabilityID("read_web_page")
}
